name: Allure Docker Service UI Workflow

on:
  push:
    branches: [ "dev", "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Determine Dockerfile to use
      id: select_dockerfile
      run: |
        echo "dockerfile=Dockerfile" >> $GITHUB_OUTPUT

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GIT_TOKEN }}

    - name: Build and push Docker image
      run: |
        if [ "${{ github.ref }}" = "refs/heads/dev" ]; then
          docker build -t ghcr.io/${{ github.repository_owner }}/allureui:dev -f ./docker/${{ steps.select_dockerfile.outputs.dockerfile }} .
          docker push ghcr.io/${{ github.repository_owner }}/allureui:dev
        elif [ "${{ github.ref }}" = "refs/heads/master" ]; then
          docker build -t ghcr.io/${{ github.repository_owner }}/allureui:main -f ./docker/${{ steps.select_dockerfile.outputs.dockerfile }} .
          docker push ghcr.io/${{ github.repository_owner }}/allureui:main
        fi

    - name: Remove the local image
      run: docker rmi allureui:latest
