name: Allure Docker Service UI Workflow

on:
  push:
    branches: [ "dev", "master" ]

# Configuración de concurrencia por rama
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Determine Dockerfile to use
      id: select_dockerfile
      run: |
        if [ "${GITHUB_REF##*/}" = "main" ]; then
          echo "::set-output name=dockerfile::Dockerfile"
        elif [ "${GITHUB_REF##*/}" = "dev" ]; then
          echo "::set-output name=dockerfile::Dockerfile-dev"
        fi

    - name: Build the Docker image
      run: docker build -t allureui:latest -f ./docker/${{ steps.select_dockerfile.outputs.dockerfile }} .

    - name: Log into GitHub Packages Docker Registry
      run: docker login docker.pkg.github.com -u legnadev --password "${{ secrets.GIT_TOKEN }}"

    - name: Tag and Push image based on branch
      run: |
        if [ "${{ github.ref }}" = "refs/heads/dev" ]; then
          docker tag allureui:latest docker.pkg.github.com/${{ github.repository }}/allureui:dev
          docker push docker.pkg.github.com/${{ github.repository }}/allureui:dev
        elif [ "${{ github.ref }}" = "refs/heads/main" ]; then
          docker tag allureui:latest docker.pkg.github.com/${{ github.repository }}/allureui:main
          docker push docker.pkg.github.com/${{ github.repository }}/allureui:main
        fi

    - name: Remove the local image
      run: docker rmi allureui:latest
